// <auto-generated />
using System;
using CarComparisonApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarComparisonApi.Migrations
{
    [DbContext(typeof(CarComparisonDbContext))]
    [Migration("20260511120000_RemoveGenerationNameAndDoorsCountFromSearchCars")]
    partial class RemoveGenerationNameAndDoorsCountFromSearchCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a minimal designer file for a migration that only touches SearchCars
            // The actual model state is in CarComparisonDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
