// <auto-generated />
using System;
using CarComparisonApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarComparisonApi.Migrations
{
    [DbContext(typeof(CarComparisonDbContext))]
    [Migration("20260507100957_RemoveGenerationTable")]
    partial class RemoveGenerationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarComparisonApi.Models.BodyStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BodyStyles");
                });

            modelBuilder.Entity("CarComparisonApi.Models.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");
                });

            modelBuilder.Entity("CarComparisonApi.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("CarComparisonApi.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrimId");

                    b.HasIndex("UserId", "TrimId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("CarComparisonApi.Models.GenerationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenerationVariantId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenerationVariantId");

                    b.HasIndex("GenerationVariantId", "SortOrder");

                    b.ToTable("GenerationImages");
                });

            modelBuilder.Entity("CarComparisonApi.Models.GenerationVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyStyleId")
                        .HasColumnType("int");

                    b.Property<int>("DoorsCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VariantType")
                        .HasColumnType("int");

                    b.Property<int>("YearFrom")
                        .HasColumnType("int");

                    b.Property<int>("YearTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodyStyleId");

                    b.HasIndex("ModelId");

                    b.HasIndex("ModelId", "VariantType", "BodyStyleId", "DoorsCount");

                    b.ToTable("GenerationVariants");
                });

            modelBuilder.Entity("CarComparisonApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TrimId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrimId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CarComparisonApi.Models.SearchCar", b =>
                {
                    b.Property<long>("SearchCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SearchCarId"));

                    b.Property<int?>("BodyStyleId")
                        .HasColumnType("int");

                    b.Property<string>("BodyStyleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoorsCount")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.Property<string>("GenerationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenerationVariantId")
                        .HasColumnType("int");

                    b.Property<string>("GenerationVariantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopularityScore")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrimId")
                        .HasColumnType("int");

                    b.Property<string>("TrimName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("VariantType")
                        .HasColumnType("int");

                    b.Property<int>("YearFrom")
                        .HasColumnType("int");

                    b.Property<int>("YearTo")
                        .HasColumnType("int");

                    b.HasKey("SearchCarId");

                    b.HasIndex("TrimId")
                        .IsUnique();

                    b.HasIndex("YearFrom", "YearTo", "SearchCarId")
                        .HasDatabaseName("IX_SearchCars_YearRange")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("BrandId", "ModelId", "PopularityScore", "SearchCarId")
                        .HasDatabaseName("IX_SearchCars_Popularity")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("BrandId", "ModelId", "GenerationId", "YearFrom", "YearTo", "SearchCarId")
                        .HasDatabaseName("IX_SearchCars_FilterCore")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("BrandId", "ModelId", "GenerationId", "BodyStyleId", "VariantType", "FuelType", "TransmissionType")
                        .HasDatabaseName("IX_SearchCars_Facets")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("SearchCars");
                });

            modelBuilder.Entity("CarComparisonApi.Models.TechnicalDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Acceleration0To100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CompressionRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurbWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CylindersCount")
                        .HasColumnType("int");

                    b.Property<string>("DriveType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ElectricRange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EngineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EngineDisplacement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EngineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontBrakes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontSuspension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FrontTrack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuelConsumptionCity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuelConsumptionHighway")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuelConsumptionMixed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuelTankCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GrossWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxPowerAtRPM")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTorqueAtRPM")
                        .HasColumnType("int");

                    b.Property<int?>("Power")
                        .HasColumnType("int");

                    b.Property<string>("RearBrakes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RearSuspension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RearTrack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Torque")
                        .HasColumnType("int");

                    b.Property<int>("TrimId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TurningCircle")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ValvesCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Wheelbase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TrimId")
                        .IsUnique();

                    b.ToTable("TechnicalDetails");
                });

            modelBuilder.Entity("CarComparisonApi.Models.Trim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DoorsCount")
                        .HasColumnType("int");

                    b.Property<int>("GenerationVariantId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeatsCount")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenerationVariantId");

                    b.ToTable("Trims");
                });

            modelBuilder.Entity("CarComparisonApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarComparisonApi.Models.CarModel", b =>
                {
                    b.HasOne("CarComparisonApi.Models.CarBrand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarComparisonApi.Models.Favorite", b =>
                {
                    b.HasOne("CarComparisonApi.Models.Trim", "Trim")
                        .WithMany("Favorites")
                        .HasForeignKey("TrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarComparisonApi.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarComparisonApi.Models.GenerationImage", b =>
                {
                    b.HasOne("CarComparisonApi.Models.GenerationVariant", "GenerationVariant")
                        .WithMany("Images")
                        .HasForeignKey("GenerationVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationVariant");
                });

            modelBuilder.Entity("CarComparisonApi.Models.GenerationVariant", b =>
                {
                    b.HasOne("CarComparisonApi.Models.BodyStyle", "BodyStyle")
                        .WithMany("GenerationVariants")
                        .HasForeignKey("BodyStyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarComparisonApi.Models.CarModel", "Model")
                        .WithMany("GenerationVariants")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyStyle");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarComparisonApi.Models.Review", b =>
                {
                    b.HasOne("CarComparisonApi.Models.Trim", "Trim")
                        .WithMany("Reviews")
                        .HasForeignKey("TrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarComparisonApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarComparisonApi.Models.TechnicalDetails", b =>
                {
                    b.HasOne("CarComparisonApi.Models.Trim", "Trim")
                        .WithOne("TechnicalDetails")
                        .HasForeignKey("CarComparisonApi.Models.TechnicalDetails", "TrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trim");
                });

            modelBuilder.Entity("CarComparisonApi.Models.Trim", b =>
                {
                    b.HasOne("CarComparisonApi.Models.GenerationVariant", "GenerationVariant")
                        .WithMany("Trims")
                        .HasForeignKey("GenerationVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationVariant");
                });

            modelBuilder.Entity("CarComparisonApi.Models.BodyStyle", b =>
                {
                    b.Navigation("GenerationVariants");
                });

            modelBuilder.Entity("CarComparisonApi.Models.CarBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("CarComparisonApi.Models.CarModel", b =>
                {
                    b.Navigation("GenerationVariants");
                });

            modelBuilder.Entity("CarComparisonApi.Models.GenerationVariant", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Trims");
                });

            modelBuilder.Entity("CarComparisonApi.Models.Trim", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("TechnicalDetails");
                });

            modelBuilder.Entity("CarComparisonApi.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
